### ISSUE TITLE
Общие вопросы

### ISSUE THREAD

**Issue by DamirZaripov16** [DamirZaripov16/interpreter#1]
@coursar Ильназ, подскажите следующее, пожалуйста:
1. Хотелось бы записывать текст в textarea, а не в input  - с addEventListener'ами проблем не возникнет? Т.е. события тоже будут "input"?
2. Нужно ли на второй textarea делать addEventListener на добавление текста из первой textarea или он просто должен отражать textContent'ом преобразованное содержимое первой textarea?
3. В начале нужно создать объект, где, к примеру "ж": "g" итд?
4. Как при нажатии button преобразовать текст на кириллице в первой textarea  в текст на латинице во втором textarea?

**Comment by coursar** [comment]
1. Попробуйте, не должно
1. Сделаете её readonly (атрибут)
1. Наверное, да
1. Это вопрос к вам )) вы же придумали подобный алгоритм

**Comment by DamirZaripov16** [comment]
@coursar Ильназ, проверьте, пожалуйста.
Написал функцию на транслит (немного старого образца), не выводит транслит текста. Подскажите, что не так

**Comment by DamirZaripov16** [comment]
@coursar Ильназ, проверьте, пожалуйста.
Написал функцию на транслит (немного старого образца), не выводит транслит текста. Подскажите, что не так

**Comment by DamirZaripov16** [comment]
@coursar Ильназ, подскажите, пожалуйста, как при переводе сохранить исходные символы? Т.е. чтобы при переводе "-" = "-", "*"="*" итд? Неужели придется все эти символы тоже вносить в объект transl?
https://github.com/DamirZaripov16/interpreter/blob/cf5fdc8c09993129874e0e1201033ae001b13ded/src/app/interpreterV2.js#L30-L40

**Comment by coursar** [comment]
Самый простой вариант - вам нужно посимвольное сопоставление и по символам заменять

**Comment by DamirZaripov16** [comment]
@coursar Понял, а регистр изменить не получится? (Day === Дэй, NIGHT === НАЙТ; итд)

**Comment by DamirZaripov16** [comment]
@coursar Понял. Ильназ, подскажите на примере как сделать поиск на другом сайте у себя в приложении?

**Comment by DamirZaripov16** [comment]
@coursar Понял, спасибо. Тот вопрос снят) 
Не подскажите, как поменять поля местами (чтобы можно было переводить не только, к примеру рус-анг, но и анг-рус)?

**Comment by DamirZaripov16** [comment]
@coursar Будет ли выходом просто создать еще и обратный объект-словарь и сделать такой же цикл, как и в случае с первым?

**Comment by coursar** [comment]
Да, вам по факту нужно только надписи поменять через DOM (и где-то внутри приложения хранить направление перевода).

Да, это как в словаре - есть англо-русский, есть русско-английский.

**Comment by DamirZaripov16** [comment]
@coursar Я пробовал реализовать подобное, но получалось что-то вроде этого: счастье --> счастьеschastye. Не подскажите, в чем проблема?

**Comment by coursar** [comment]
скиньте ссылку на кусок, где вы это делаете - разберёмся

**Comment by DamirZaripov16** [comment]
https://github.com/DamirZaripov16/interpreter/blob/563cc089cda64b2ea60f81e5caf67344a378f60c/src/app/interpreter.js#L151-L161

**Comment by coursar** [comment]
надо выложить куда-то, чтобы я мог воспроизвести, сейчас у вас на хероку версия, в которой это не воспроизводится

**Comment by DamirZaripov16** [comment]
https://damirzaripov16.github.io/interpreter/ на хероку я еще не мог поставить. а через githubpages работает, вроде

**Comment by coursar** [comment]
Я про проблему - где проблема-то проявляется, что нельзя обратно сделать?

**Comment by DamirZaripov16** [comment]
Эта функция не реализована. Указанная проблема появляется, если добавить обратный словарь и такой же цикл, только поменяв содержимое условия "if" с содержимым условия "else if" https://github.com/DamirZaripov16/interpreter/blob/563cc089cda64b2ea60f81e5caf67344a378f60c/src/app/interpreter.js#L152-L155
